# fly.toml file generated for canvas-hub-daemon on 2023-03-20T12:53:39Z

app = "canvas-hub-daemon"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]
  CANVAS_HOME = "/data"
  END_PORT = "57344"
  PORT = "8000"
  PROXY_PORT = "8080"
  START_PORT = "49152"

[metrics]
  path = "/metrics"
  port = 8000

[mounts]
  destination = "/data"
  source = "data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 100
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    start_port = 49152
