# fly.toml file generated for canvas-hub-daemon on 2022-12-19T10:47:10-05:00

app = "canvas-hub-daemon"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]
  PORT = "8000"
  CANVAS_HOME = "/data"

[mounts]
  source = "data"
  destination = "/data"

[metrics]
  path = "/metrics"
  port = 8000

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 100
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    start_port = 49152
    end_port = 65535
