name: CI
on: [push]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout canvas-hub-daemon
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install canvas-hub-daemon
        run: |
          npm ci
          npm run build
